
kind: pipeline
type: docker
name: default

steps:
- name: Restore-cache
  image: drillster/drone-volume-cache
  restore: true
  mount:
  - ./.npm-cache
  - ./node_modules
  volumes:
  - name: cache
    path: /tmp/cache

- name: Install package
  image: node:alpine
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - npm config set cache-folder .npm-cache
  - npm install --pure-lockfile

- name: Publish
  image: plugins/docker
  settings:
    auto_tag: true
    repo: tungduy/nodejs-etutor
    dockerfile: Dockerfile
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    
- name: Transfer-compose
  image: appleboy/drone-scp
  settings:
    host: drone.e-tutor.wtf
    port: 22
    username: fbeta
    password:
      from_secret: server_password
    target:  /home/e-tutor/${DRONE_REPO_NAME}
    source:
      - docker-compose.yml
      - docker-compose.prod.yml
  when:
    branch: master

- name: Run Images
  image: appleboy/drone-ssh
  settings:
    host: drone.e-tutor.wtf
    port: 22
    command_timeout: 6m
    username: fbeta
    password:
      from_secret: server_password
    script:
      # - . ~/project/.script/deploy.sh tungduy/nodejs-etutor
      - cd /home/e-tutor/${DRONE_REPO_NAME}
      - docker-compose down
      - docker rmi -f tungduy/nodejs-etutor
      - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d                                                      
  when:
    branch:
      - master
    event:
      - push
    status:
      - success

- name: Slack send massage
  image: plugins/slack
  settings:
    webhook:
      from_secret: webhook_slack
    channel: drone-notify
    username: drone
    icon_emoji: ':bowtie:'
    link_names: true
    template: >
      {{#success build.status}}
        Build {{build.number}} succeeded and deployed to Production! :)
        Event: {{build.event}}
        Branch: {{build.branch}}
        Tag: {{build.tag}}
        Git SHA: {{build.commit}}
        Link: {{build.link}}
      {{else}}
        Build {{build.number}} failed and not deployed to Production :(
        Event: {{build.event}}
        Branch: {{build.branch}}
        Tag: {{build.tag}}
        Git SHA: {{build.commit}}
        Link: {{build.link}}
      {{/success}}
  when:
    status:
      - success
      - failure

- name: Rebuild-cache
  image: drillster/drone-volume-cache
  rebuild: true
  mount:
  - ./node_modules
  - ./.npm-cache
  volumes:
  - name: cache
    path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/lib/cache
