version: '3'
services:
  web:
    container_name: nodejs-etutor
    ports: 
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      SECRET_EXPIRES: ${SECRET_EXPIRES}
      SECRET: ${SECRET}
      DB_URI: "mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?authSource=admin"
    networks: 
      - fbeta-networks
networks: 
  fbeta-networks:
    external: true