# development
version: '3'
services: 
  db:
    image: mongo
    container_name: mongo_local
    volumes: 
      - db-local:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    networks: 
      - fbeta-networks
  mongo-express:
    image: mongo-express
    container_name: mongo-express-local
    ports: 
      - "8888:8081"
    depends_on:
      - db
    environment: 
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootPassword
      ME_CONFIG_BASICAUTH_USERNAME: namthit98
      ME_CONFIG_BASICAUTH_PASSWORD: dev@123
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    networks: 
      - fbeta-networks
  web:
    build:
      context: .
    container_name: node-app-local
    volumes: 
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    environment: 
      NODE_ENV: 'development'
    depends_on: 
      - db
volumes:
  db-local: